# Generated by Django 6.0.2 on 2026-02-14 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_etiqueta', models.CharField(max_length=100)),
                ('url_audio', models.CharField(max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'audios_venta',
            },
        ),
        migrations.CreateModel(
            name='EstadoAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'estados_audios',
            },
        ),
        migrations.CreateModel(
            name='EstadoSOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('es_final', models.BooleanField(default=False)),
                ('color_hex', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'estados_sot',
            },
        ),
        migrations.CreateModel(
            name='GrabadorAudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'grabadores_audios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=100)),
                ('es_alto_valor', models.BooleanField(default=False)),
                ('costo_fijo_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comision_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio_vigencia', models.DateField(auto_now_add=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=20)),
                ('cliente_numero_doc', models.CharField(max_length=20)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_genero', models.CharField(max_length=20, null=True)),
                ('cliente_fecha_nacimiento', models.DateField(null=True)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_telefono_2', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion_detalle', models.CharField(max_length=255)),
                ('direccion_referencia', models.CharField(blank=True, max_length=255, null=True)),
                ('coordenadas_gps', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_sec', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_sot', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('fecha_real_inst', models.DateTimeField(blank=True, null=True)),
                ('comentario_gestion', models.TextField(blank=True, null=True)),
                ('audio_subido', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ventas',
            },
        ),
    ]
