# Generated by Django 6.0.2 on 2026-02-18 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('sales', '0001_initial'),
        ('ubigeo', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grabadoraudio',
            name='id_usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialagendasot',
            name='usuario_responsable',
            field=models.ForeignKey(db_column='usuario_responsable', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialagendasot',
            name='id_sub_estado_motivo',
            field=models.ForeignKey(db_column='id_sub_estado_motivo', on_delete=django.db.models.deletion.PROTECT, to='sales.subestadosot'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_asesor',
            field=models.ForeignKey(db_column='id_asesor', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_asesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_distrito_instalacion',
            field=models.ForeignKey(db_column='id_distrito_instalacion', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_instalacion', to='ubigeo.distrito'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_distrito_nacimiento',
            field=models.ForeignKey(db_column='id_distrito_nacimiento', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_nacimiento', to='ubigeo.distrito'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_estado_audios',
            field=models.ForeignKey(db_column='id_estado_audios', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.estadoaudio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_estado_sot',
            field=models.ForeignKey(db_column='id_estado_sot', on_delete=django.db.models.deletion.PROTECT, to='sales.estadosot'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_grabador_audios',
            field=models.ForeignKey(db_column='id_grabador_audios', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.grabadoraudio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_origen_venta',
            field=models.ForeignKey(db_column='id_origen_venta', on_delete=django.db.models.deletion.PROTECT, to='core.modalidadsede'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='sales.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_sub_estado_sot',
            field=models.ForeignKey(db_column='id_sub_estado_sot', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.subestadosot'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_supervisor_vigente',
            field=models.ForeignKey(db_column='id_supervisor_vigente', on_delete=django.db.models.deletion.PROTECT, to='users.supervisorasignacion'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_tipo_documento',
            field=models.ForeignKey(db_column='id_tipo_documento', on_delete=django.db.models.deletion.PROTECT, to='core.tipodocumento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_creacion',
            field=models.ForeignKey(db_column='usuario_creacion', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_modificacion',
            field=models.ForeignKey(db_column='usuario_modificacion', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_modificadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_revision_audios',
            field=models.ForeignKey(db_column='usuario_revision_audios', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audios_revisados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialagendasot',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='historial_agenda', to='sales.venta'),
        ),
        migrations.AddField(
            model_name='audioventa',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='sales.venta'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['fecha_visita_programada', 'id_sub_estado_sot'], name='idx_filtro_agenda'),
        ),
    ]
