# Generated by Django 6.0.2 on 2026-02-12 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0002_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='id_asesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_asesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_estado_audios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.estadoaudio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_estado_sot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.estadosot'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_grabador_audios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.grabadoraudio'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_origen_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.modalidadsede'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_supervisor_vigente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.supervisorasignacion'),
        ),
        migrations.AddField(
            model_name='venta',
            name='id_tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.tipodocumento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='usuario_creacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='audioventa',
            name='id_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='sales.venta'),
        ),
    ]
