# Generated by Django 5.2.7 on 2026-03-03 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='venta_origen',
            field=models.ForeignKey(blank=True, db_column='venta_origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_derivadas', to='sales.venta'),
        ),
    ]
