# Generated by Django 6.0.2 on 2026-02-21 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_fecha_nacimiento',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 12, 5, 31, 994615, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_mama',
            field=models.CharField(default='SIN DATO', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente_papa',
            field=models.CharField(default='SIN DATO', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_instalacion',
            field=models.CharField(default='SIN DATO', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='plano',
            field=models.CharField(default='SIN DATO', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='referencias',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='representante_legal_dni',
            field=models.CharField(blank=True, help_text='DNI del titular. Solo si es RUC', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='representante_legal_nombre',
            field=models.CharField(blank=True, help_text='Nombre del titular', max_length=200, null=True),
        ),
    ]
