# Generated by Django 5.2.7 on 2026-03-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_venta_venta_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_plan',
        ),
    ]
