# Generated by Django 6.0.2 on 2026-02-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_venta_cliente_fecha_nacimiento_venta_cliente_mama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioventa',
            name='conforme',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audioventa',
            name='motivo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
