# Generated by Django 5.2.7 on 2026-03-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_venta_nombre_grabador_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_genero',
            field=models.CharField(default='NO ESPECIFICADO', max_length=20),
        ),
    ]
