# Generated by Django 6.0.2 on 2026-02-23 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_audioventa_conforme_audioventa_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='audioventa',
            name='corregido',
            field=models.BooleanField(default=False),
        ),
    ]
