# Generated by Django 6.0.2 on 2026-02-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_audioventa_corregido'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='solicitud_correccion',
            field=models.BooleanField(default=False),
        ),
    ]
