# Generated by Django 5.2.7 on 2026-03-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_venta_cliente_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='permitir_reingreso',
            field=models.BooleanField(default=False, help_text='Si es True y la venta está RECHAZADA, el asesor podrá crear un reingreso.'),
        ),
    ]
