# Generated by Django 6.0.2 on 2026-02-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_venta_solicitud_correccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='tipo_venta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
