# Generated by Django 6.0.2 on 2026-03-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_venta_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_campana',
            field=models.CharField(default='POR ACTUALIZAR', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='nombre_paquete',
            field=models.CharField(default='POR ACTUALIZAR', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_solucion',
            field=models.CharField(default='POR ACTUALIZAR', max_length=50),
            preserve_default=False,
        ),
    ]
