# Generated by Django 5.2.7 on 2026-02-26 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_venta_tipo_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='venta_origen',
            field=models.ForeignKey(blank=True, db_column='venta_origen_id', help_text='Si es un reingreso, apunta a la venta RECHAZADA original.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reingresos', to='sales.venta'),
        ),
    ]
