# Generated by Django 5.2.7 on 2026-02-28 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_venta_venta_origen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='venta_origen',
        ),
    ]
