# Generated by Django 6.0.2 on 2026-03-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_producto_nombre_campana_producto_nombre_paquete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cant_decos_adicionales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='cant_repetidores_adicionales',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venta',
            name='venta_origen',
            field=models.ForeignKey(blank=True, db_column='venta_origen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_derivadas', to='sales.venta'),
        ),
    ]
