# Generated by Django 6.0.2 on 2026-03-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_venta_cant_decos_adicionales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombre_plan',
        ),
    ]
