# Generated by Django 5.2.7 on 2026-03-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_producto_nombre_campana_producto_nombre_paquete_and_more'),
        ('sales', '0010_remove_venta_venta_origen'),
    ]

    operations = [
    ]
