# Generated by Django 6.0.2 on 2026-03-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_remove_producto_nombre_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_grabador_externo',
            field=models.CharField(blank=True, help_text='Se llena manualmente solo si el id_grabador_audios es 1 (OTROS)', max_length=150, null=True),
        ),
    ]
