# Generated by Django 6.0.2 on 2026-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_venta_nombre_grabador_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='cliente_genero',
            field=models.CharField(choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('NO ESPECIFICADO', 'No Especificado')], default='NO ESPECIFICADO', max_length=20),
        ),
    ]
