# Generated by Django 6.0.2 on 2026-04-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_venta_permitir_reingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
