# Generated by Django 6.0.2 on 2026-06-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_venta_fecha_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='comision_base',
            new_name='comision_base_call',
        ),
    ]
