# Generated by Django 6.0.2 on 2026-06-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_rename_comision_base_producto_comision_base_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='comision_base_campo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Comisión si la venta se hizo en modalidad CAMPO. Dejar en blanco si no aplica.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='comision_base_call',
            field=models.DecimalField(decimal_places=2, help_text='Comisión si la venta se hizo en modalidad CALL', max_digits=10),
        ),
    ]
