# Generated by Django 6.0.2 on 2026-02-12 05:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escala', models.CharField(max_length=100)),
                ('minimo_ventas_requeridas', models.IntegerField()),
                ('sueldo_base_nivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meta_alto_valor_requerida', models.IntegerField()),
                ('porcentaje_comision_full', models.DecimalField(decimal_places=2, max_digits=5)),
                ('porcentaje_comision_penalizada', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='CALL, CAMPO', max_length=50)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=150)),
                ('es_alto_valor', models.BooleanField(default=False)),
                ('comision_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReglaSalarialMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dias_laborables_mes', models.IntegerField(default=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('rol_sistema', models.CharField(choices=[('DUENO', 'Dueño'), ('ASESOR', 'Asesor'), ('BACKOFFICE', 'BackOffice'), ('RRHH', 'RRHH')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='LiquidacionMensualAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('total_ventas_instaladas', models.IntegerField()),
                ('total_alto_valor_logradas', models.IntegerField()),
                ('dias_falta', models.IntegerField()),
                ('monto_descuento_inasistencias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cumplio_meta_alto_valor', models.BooleanField()),
                ('porcentaje_comision_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('monto_total_comisiones', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_final_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_calculo', models.DateTimeField(auto_now=True)),
                ('escala_alcanzada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.escalasueldo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModalidadSede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_supervisor', models.CharField(help_text='Ej: Juan Perez (Supervisor de JLO-Call)', max_length=200)),
                ('activo', models.BooleanField(default=True)),
                ('modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidad')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='PermisoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidad_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.modalidadsede')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='escalasueldo',
            name='regla_salarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.reglasalarialmensual'),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField(null=True)),
                ('hora_salida', models.TimeField(null=True)),
                ('estado', models.CharField(max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecnologia', models.CharField(max_length=20)),
                ('costo_fijo_plan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cliente_tipo_doc', models.CharField(max_length=20)),
                ('cliente_numero_doc', models.CharField(max_length=20)),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_genero', models.CharField(blank=True, max_length=20)),
                ('cliente_fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('cliente_telefono_2', models.CharField(blank=True, max_length=20)),
                ('cliente_email', models.CharField(blank=True, max_length=100)),
                ('nacimiento_departamento', models.CharField(blank=True, max_length=100)),
                ('nacimiento_provincia', models.CharField(blank=True, max_length=100)),
                ('nacimiento_distrito', models.CharField(blank=True, max_length=100)),
                ('nombre_padre', models.CharField(blank=True, max_length=200)),
                ('nombre_madre', models.CharField(blank=True, max_length=200)),
                ('direccion_departamento', models.CharField(blank=True, max_length=100)),
                ('direccion_provincia', models.CharField(blank=True, max_length=100)),
                ('direccion_distrito', models.CharField(blank=True, max_length=100)),
                ('direccion_detalle', models.TextField(blank=True)),
                ('direccion_referencia', models.TextField(blank=True)),
                ('coordenadas_gps', models.CharField(blank=True, max_length=100)),
                ('plano_ubicacion', models.CharField(blank=True, max_length=255)),
                ('es_full_claro', models.BooleanField(default=False)),
                ('score_crediticio', models.CharField(blank=True, max_length=50)),
                ('codigo_sec', models.CharField(blank=True, max_length=50)),
                ('codigo_sot', models.CharField(blank=True, max_length=50)),
                ('codigo_pago', models.CharField(blank=True, max_length=50)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_propuesta_inst', models.DateTimeField(blank=True, null=True)),
                ('fecha_real_inst', models.DateTimeField(blank=True, null=True)),
                ('fecha_rechazo', models.DateTimeField(blank=True, null=True)),
                ('estado_sot', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Ejecucion', 'Ejecución'), ('Instalada', 'Instalada'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=20)),
                ('comentario_gestion', models.TextField(blank=True)),
                ('audio_subido', models.BooleanField(default=False)),
                ('estado_audios_general', models.CharField(blank=True, max_length=50)),
                ('fecha_subida_audios_general', models.DateTimeField(blank=True, null=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('origen_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.modalidadsede')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='AudioVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_audio', models.CharField(max_length=500)),
                ('nombre_etiqueta', models.CharField(max_length=100)),
                ('fecha_expiracion', models.DateTimeField(blank=True, null=True)),
                ('backup_realizado', models.BooleanField(default=False)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='core.venta')),
            ],
        ),
    ]
