# Generated by Django 6.0.2 on 2026-02-14 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ubigeo', models.CharField(max_length=2, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ubigeo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provincias', to='ubigeo.departamento')),
            ],
            options={
                'db_table': 'provincias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ubigeo', models.CharField(help_text='UBIGEO completo INEI', max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('id_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distritos', to='ubigeo.provincia')),
            ],
            options={
                'db_table': 'distritos',
                'ordering': ['nombre'],
            },
        ),
    ]
