# Generated by Django 6.0.2 on 2026-06-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modalidad',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
