# Generated by Django 6.0.2 on 2026-06-16 06:06

from django.db import migrations


def poblar_codigos(apps, schema_editor):
    # OJO: Cambia 'core' por el nombre real de la app donde está Modalidad
    Modalidad = apps.get_model('core', 'Modalidad')

    for modalidad in Modalidad.objects.all():
        nombre_upper = modalidad.nombre.upper()
        if 'CALL' in nombre_upper:
            modalidad.codigo = 'CALL'
        elif 'CAMPO' in nombre_upper:
            modalidad.codigo = 'CAMPO'
        else:
            # Salvavidas: Si hay otra modalidad, le pone su ID para evitar errores de unicidad luego
            modalidad.codigo = f"MOD_{modalidad.id}"

        modalidad.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_modalidad_codigo'),
    ]

    operations = [
        # Ejecutamos nuestra inyección de datos
        migrations.RunPython(poblar_codigos),
    ]
