# Generated by Django 6.0.2 on 2026-06-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20260616_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalidad',
            name='codigo',
            field=models.CharField(help_text='Identificador técnico inmutable. Ej: CALL, CAMPO. NO cambiar una vez creado.', max_length=20, unique=True),
        ),
    ]
