# Generated by Django 6.0.2 on 2026-02-13 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_asistencia'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='users.rolsistema'),
        ),
        migrations.CreateModel(
            name='PermisoAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modalidad_sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.modalidadsede')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'permisos_acceso',
            },
        ),
    ]
