# Generated by Django 6.0.2 on 2026-06-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_celular_usuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, help_text='Documento Nacional de Identidad o Carné de Extranjería', max_length=15, null=True, unique=True),
        ),
    ]
