# Generated by Django 6.0.2 on 2026-02-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaComisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_origen', models.IntegerField()),
                ('anio_origen', models.IntegerField()),
                ('total_ventas_pagadas', models.IntegerField()),
                ('monto_bruto_generado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factor_aplicado', models.DecimalField(decimal_places=2, max_digits=3)),
                ('monto_neto_guardado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagado', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bolsa_comisiones',
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMensualAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('anio', models.IntegerField()),
                ('total_instaladas_mes', models.IntegerField()),
                ('sueldo_base_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_comisiones_pagado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_descuento_inasistencias', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monto_final_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'liquidacion_mensual_asesor',
            },
        ),
        migrations.CreateModel(
            name='ReglaRendimientoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('min_instaladas', models.IntegerField()),
                ('max_instaladas', models.IntegerField()),
                ('activa_sueldo_ft', models.BooleanField(default=False)),
                ('monto_sueldo_ft', models.DecimalField(decimal_places=2, default=1120.0, max_digits=10)),
                ('factor_comision_futura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reglas_rendimiento_mensual',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.PROTECT, to='core.sucursal')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
    ]
