# Generated by Django 6.0.2 on 2026-02-14 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalaSueldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_escala', models.CharField(max_length=50)),
                ('minimo_ventas_requeridas', models.IntegerField()),
                ('sueldo_base_nivel', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'escalas_sueldo',
            },
        ),
        migrations.CreateModel(
            name='ReglaSalarialMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dias_laborables_mes', models.IntegerField(default=30)),
            ],
            options={
                'db_table': 'reglas_salariales_mensual',
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('asistio', models.BooleanField(default=False)),
                ('id_sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.sucursal')),
            ],
            options={
                'db_table': 'asistencia',
            },
        ),
    ]
