# Generated by Django 6.0.2 on 2026-02-13 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escalasueldo',
            name='id_regla_salarial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finances.reglasalarialmensual'),
        ),
    ]
