# Generated by Django 6.0.2 on 2026-02-17 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsacomisiones',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liquidacionmensualasesor',
            name='id_bolsa_pagada',
            field=models.OneToOneField(blank=True, db_column='id_bolsa_pagada', null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.bolsacomisiones'),
        ),
        migrations.AddField(
            model_name='liquidacionmensualasesor',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bolsacomisiones',
            name='id_regla_aplicada',
            field=models.ForeignKey(db_column='id_regla_aplicada', on_delete=django.db.models.deletion.PROTECT, to='finances.reglarendimientomensual'),
        ),
        migrations.AddConstraint(
            model_name='bolsacomisiones',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'mes_origen', 'anio_origen'), name='unica_bolsa_por_mes'),
        ),
    ]
