# Generated by Django 6.0.2 on 2026-05-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_asistencia_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='asistio',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
