# Generated by Django 6.0.2 on 2026-06-14 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_alter_asistencia_asistio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPlanilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_fiscal', models.PositiveSmallIntegerField(help_text='Mes en el que se DEPOSITA el dinero')),
                ('anio_fiscal', models.PositiveIntegerField()),
                ('ventas_instaladas_mes_actual', models.PositiveSmallIntegerField(help_text='Define si aplica Élite o Estándar')),
                ('ventas_pagadas_mes_anterior', models.PositiveSmallIntegerField(help_text='Define el % del pozo')),
                ('ventas_alto_valor_pagadas', models.PositiveSmallIntegerField(default=0, help_text='Define multiplicador 90/100/110')),
                ('cantidad_faltas', models.PositiveSmallIntegerField(help_text='Días de inasistencia (asistio=False)')),
                ('sueldo_base_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_pozo_aplicado', models.DecimalField(decimal_places=2, help_text='0.00, 50.00 o 100.00', max_digits=5)),
                ('multiplicador_alto_valor', models.DecimalField(decimal_places=2, help_text='90.00, 100.00 o 110.00', max_digits=5)),
                ('pozo_comisiones_bruto', models.DecimalField(decimal_places=2, help_text='Suma pura de productos antes de multiplicadores', max_digits=10)),
                ('comision_neta_ganada', models.DecimalField(decimal_places=2, help_text='Pozo * % Pozo * Multiplicador', max_digits=10)),
                ('descuento_inasistencias', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sueldo_neto_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_liquidacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fin_historico_planilla',
            },
        ),
        migrations.CreateModel(
            name='ReglaComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(help_text='Mes/Año desde que rige esta regla (Día 1)')),
                ('escenario', models.CharField(choices=[('ESTANDAR', 'Escenario Estándar (< 20 Inst.)'), ('ELITE', 'Escenario Élite (>= 20 Inst.)')], max_length=15)),
                ('min_ventas_pagadas_medio', models.PositiveIntegerField(help_text='Mínimo para cobrar el 50%')),
                ('min_ventas_pagadas_optimo', models.PositiveIntegerField(help_text='Mínimo para cobrar el 100%')),
                ('alto_valor_nivel_1', models.PositiveIntegerField(help_text='Cantidad mínima para NO ser castigado al 90% (o mantener 90% en élite)')),
                ('alto_valor_nivel_2', models.PositiveIntegerField(help_text='Cantidad para subir a 100%')),
                ('alto_valor_nivel_3', models.PositiveIntegerField(help_text='Cantidad para subir a 110%')),
                ('sueldo_base_elite', models.DecimalField(decimal_places=2, default=1130.0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'fin_regla_comision',
                'ordering': ['-periodo_inicio'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='bolsacomisiones',
            name='unica_bolsa_por_mes',
        ),
        migrations.AddField(
            model_name='historicoplanilla',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicoplanilla',
            name='procesado_por',
            field=models.ForeignKey(db_column='procesado_por', on_delete=django.db.models.deletion.PROTECT, related_name='planillas_procesadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='bolsacomisiones',
            name='id_regla_aplicada',
        ),
        migrations.RemoveField(
            model_name='bolsacomisiones',
            name='id_usuario',
        ),
        migrations.DeleteModel(
            name='LiquidacionMensualAsesor',
        ),
        migrations.AddConstraint(
            model_name='historicoplanilla',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'mes_fiscal', 'anio_fiscal'), name='unica_planilla_por_mes'),
        ),
        migrations.DeleteModel(
            name='ReglaRendimientoMensual',
        ),
        migrations.DeleteModel(
            name='BolsaComisiones',
        ),
    ]
