# Generated by Django 6.0.2 on 2026-06-14 05:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_historicoplanilla_reglacomision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoplanilla',
            name='mes_fiscal',
            field=models.PositiveSmallIntegerField(help_text='Mes en el que se DEPOSITA el dinero', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='historicoplanilla',
            name='multiplicador_alto_valor',
            field=models.DecimalField(decimal_places=2, help_text='Factor matemático: 0.90, 1.00 o 1.10', max_digits=4),
        ),
        migrations.AlterField(
            model_name='historicoplanilla',
            name='porcentaje_pozo_aplicado',
            field=models.DecimalField(decimal_places=2, help_text='Factor matemático: 0.00, 0.50 o 1.00', max_digits=4),
        ),
        migrations.AlterField(
            model_name='historicoplanilla',
            name='procesado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planillas_procesadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='reglacomision',
            constraint=models.UniqueConstraint(fields=('periodo_inicio', 'escenario'), name='unica_regla_por_periodo_escenario'),
        ),
    ]
