# Generated by Django 6.0.2 on 2026-06-17 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_modalidad_codigo'),
        ('finances', '0006_alter_historicoplanilla_mes_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reglacomision',
            name='unica_regla_por_periodo_escenario',
        ),
        migrations.AddField(
            model_name='reglacomision',
            name='id_modalidad',
            field=models.ForeignKey(blank=True, db_column='id_modalidad', help_text='Modalidad a la que aplica esta regla (Ej: CALL o CAMPO)', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.modalidad'),
        ),
        migrations.AddConstraint(
            model_name='reglacomision',
            constraint=models.UniqueConstraint(fields=('periodo_inicio', 'escenario', 'id_modalidad'), name='unica_regla_por_periodo_escenario_modalidad'),
        ),
    ]
