# Generated by Django 6.0.2 on 2026-06-17 04:24

from django.db import migrations


def poblar_modalidad_por_defecto(apps, schema_editor):
    # Traemos los modelos desde el historial de migraciones
    ReglaComision = apps.get_model('finances', 'ReglaComision')
    Modalidad = apps.get_model('core', 'Modalidad')

    # Buscamos la modalidad CALL que creamos hace un rato
    try:
        modalidad_call = Modalidad.objects.get(codigo='CALL')
    except Modalidad.DoesNotExist:
        # Salvavidas: Si no existe, la crea para que la migración no explote
        modalidad_call = Modalidad.objects.create(codigo='CALL', nombre='Call Center')

    # Le asignamos la modalidad CALL a todas las reglas históricas
    ReglaComision.objects.all().update(id_modalidad=modalidad_call)

class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_remove_reglacomision_unica_regla_por_periodo_escenario_and_more'),
    ]

    operations = [
        migrations.RunPython(poblar_modalidad_por_defecto),
    ]
