# Generated by Django 6.0.2 on 2026-06-17 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_modalidad_codigo'),
        ('finances', '0008_auto_20260616_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reglacomision',
            name='id_modalidad',
            field=models.ForeignKey(db_column='id_modalidad', help_text='Modalidad a la que aplica esta regla (Ej: CALL o CAMPO)', on_delete=django.db.models.deletion.PROTECT, to='core.modalidad'),
        ),
    ]
