# Generated by Django 6.0.2 on 2026-06-17 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_alter_reglacomision_id_modalidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoplanilla',
            name='modalidad_aplicada',
            field=models.CharField(default='CALL', help_text='Código de la modalidad evaluada en este mes (Ej: CALL, CAMPO)', max_length=20),
        ),
    ]
