# Generated by Django 6.0.2 on 2026-06-18 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_historicoplanilla_modalidad_aplicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoplanilla',
            name='sede_aplicada',
            field=models.CharField(blank=True, help_text='Nombre de la sede al momento de la liquidación (Snapshot)', max_length=150, null=True),
        ),
    ]
