# Generated by Django 6.0.2 on 2026-02-13 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 13, 6, 22, 36, 265172, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
