# Generated by Django 6.0.2 on 2026-02-17 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('ciclo_facturacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_venta', models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='sales.venta')),
            ],
            options={
                'db_table': 'seguimiento',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_numero', models.IntegerField()),
                ('pago_cliente_realizado', models.BooleanField(default=False)),
                ('fecha_validacion_pago', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('id_seguimiento', models.ForeignKey(db_column='id_seguimiento', on_delete=django.db.models.deletion.CASCADE, related_name='meses_evaluados', to='tracking.seguimiento')),
            ],
            options={
                'db_table': 'seguimiento_mensual',
            },
        ),
    ]
