# Generated by Django 6.0.2 on 2026-04-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='descuento_realizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='estado',
            field=models.CharField(blank=True, choices=[('PENALIZADO', 'Penalizado'), ('SUSPENDIDO', 'Suspendido'), ('DESACTIVADO', 'Desactivado')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='seguimientomensual',
            name='fecha_seguimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
