# Generated by Django 6.0.2 on 2026-04-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_seguimiento_descuento_realizado_seguimiento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimientomensual',
            name='conformidad',
            field=models.CharField(blank=True, choices=[('CONFORME', 'Conforme'), ('INCONFORME', 'Inconforme')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='ciclo_facturacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
