# Generated by Django 6.0.2 on 2026-04-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_seguimientomensual_conformidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='ciclo_modificado_manualmente',
            field=models.BooleanField(default=False),
        ),
    ]
